DROP TABLE IF EXISTS tasklist;
DROP TABLE IF EXISTS task;

CREATE TABLE tasklist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    description TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT 0,
    tasklist_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tasklist_id) REFERENCES tasklist (id) ON DELETE CASCADE
);
